dist: xenial

language: minimal

branches:
  only:
    - master

services:
  - docker

install: true

jobs:
  include:
    - script:
      - docker build -t lambda-packager:1 -f al1.Dockerfile .
    - script:
      - docker build -t lambda-packager:2 -f al2.Dockerfile .
