dist: xenial

language: minimal

branches:
  only:
    - master

services:
  - docker

install: skip

jobs:
  include:
    - language: minimal
      script:
        - docker build -t lambda-packager:1 -f al1.Dockerfile .
    - language: minimal
      script:
        - docker build -t lambda-packager:2 -f al2.Dockerfile .
