dist: xenial

language: minimal

branches:
  only:
    - master

services:
  - docker

install: skip

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t lambda-packager:1 -f al1.Dockerfile .
    -
      script:
        - docker build -t lambda-packager:2 -f al2.Dockerfile .
    - stage: test docker image
      script:
        - echo "Testing amazon linux 1 based image"
    -
      script:
        - echo "Testing amazon linux 2 based image"